# Site settings
title: zoom1539 Blog
SEOTitle: zoom1539的博客 | zoom1539 Blog
header-img: img/doggy.png
email: zoom1539@gmail.com
description: ""
keyword: "3D scan"
url: "https://zoom1539@github.io" 
baseurl: "" 
